NEW update button added to checkout process
silverstripe/silverstripe-dms-cart pull request #33
Opened 2017-05-31 20:45 UTC by fspringveldt

Introduced a new summary method to cart which displays it's content either in edit/view mode depending on Cart::$update setting.
This change caused issue #32 and was raised accordingly. 
Fixes #11

2017-05-31 21:30 UTC, fspringveldt commented
Codecov dropped. I'll address that pronto.

2017-06-01 01:06 UTC, sachajudd requested changes
Could you please rebase?

2017-06-01 01:06 UTC, sachajudd commented on css/dms-cart.css
> +.Actions a.action:hover{
Spaces, please follow above! (Also for line 12)

2017-06-01 01:17 UTC, robbieaverill requested changes

2017-06-01 01:17 UTC, robbieaverill commented on code/classes/DMSDocumentCart.php
> +        $this->viewOnly = (bool) $updating;
might make more sense to call this `$viewOnly`

2017-06-01 01:17 UTC, robbieaverill commented on code/classes/DMSDocumentCart.php
> +    }
Could you rubber duck the logic this method to me?

2017-06-01 01:17 UTC, robbieaverill commented on tests/controllers/DMSDocumentCartControllerTest.php
> +        $this->assertContains('You can\'t add 5 of', (string) $result->getBody());
Maybe this assertion could also cover the new "title" in the message too

2017-06-01 01:58 UTC, robbieaverill commented on tests/controllers/DMSDocumentCartControllerTest.php
> +        $this->assertInstanceOf('SS_HTTPResponse', $result);
this assertion seems a bit pointless TBH

2017-06-01 01:58 UTC, robbieaverill approved these changes

2017-06-01 02:48 UTC, sachajudd approved these changes
A few minor UX issues but these will be addressed in a later commit. Nice @fspringveldt will merge after tests.

2017-06-01 04:05 UTC, merged