FIX continue browsing button not working correctly
silverstripe/silverstripe-dms-cart pull request #35
Opened 2017-06-01 21:48 UTC by fspringveldt

Fixes #32.

2017-06-01 21:49 UTC, robbieaverill commented on code/controllers/DMSCartController.php
> +}
what's the semantic difference between a DMSDocumentCartController and a DMSCartController? If this is intended to be a base controller for both maybe call it DMSCartAbstractController or something that indicates that?

2017-06-01 21:51 UTC, fspringveldt commented on code/controllers/DMSCartController.php
> +}
Good suggestion. Yes, it is intended as a base controller. Will rename as suggested.

2017-06-01 22:02 UTC, robbieaverill commented on code/controllers/DMSCartAbstractController.php
> +}
Can we have some tests for this class?

2017-06-05 21:56 UTC, robbieaverill requested changes

2017-06-05 21:56 UTC, robbieaverill commented on tests/controllers/DMSCartAbstractControllerTest.php
> +        $this->assertSame('checkout/complete', $this->controller->Link('complete'));
This behaviour belongs in the checkout controller test class - this test class should test the logic in the abstract controller

2017-06-05 21:58 UTC, sachajudd requested changes
When 'updating' the cart items the 'continue browsing' link should go back to the documents not back into the 'checkout' page.

2017-06-06 02:03 UTC, robbieaverill approved these changes
Just @sachajudd's comments. Code wise this is good.

2017-06-06 02:03 UTC, robbieaverill commented on tests/controllers/DMSDocumentCartControllerTest.php
> +    }
This change seems redundant, but is just copy pasting. Please avoid in future.

2017-06-06 04:04 UTC, sachajudd approved these changes

2017-06-06 04:04 UTC, merged